### ISSUE TITLE
GUI Konzept überlegen (Aussehen, Buttons)

### ISSUE THREAD

**Issue by Injodikaran** [Injodikaran/Sudoku#15]
Mock-up gestalten

**Comment by Injodikaran** [comment]
@Bruelisauer 
@sedi01 
@RicoPauli

**Comment by Injodikaran** [comment]
Verschiedene Arten von bereits vorhandenen Sudoku spielen:
https://www.welt.de/spiele/online-spiele/article1336655/Sudoku.html
http://sudoku.tagesspiegel.de/sudoku-leicht/
https://www.nzz.ch/spiele/sudoku/ <- beide gleich -> http://www.sueddeutsche.de/app/spiele/sudoku/
http://www.spiegel.de/wissenschaft/mensch/sudoku-online-kostenlos-spielen-a-994416.html
http://de.websudoku.com/

**Comment by RicoPauli** [comment]
Designs
http://www.jroller.com/DhilshukReddy/

**Comment by Injodikaran** [comment]
Ähnlich wie :https://www.welt.de/spiele/online-spiele/article1336655/Sudoku.html

**Comment by Injodikaran** [comment]
GUI von Roman wird als Basis verwendet und weiter verarbeitet
