### ISSUE TITLE
Algorithmus Konzipieren

### ISSUE THREAD

**Issue by Injodikaran** [Injodikaran/Sudoku#19]

**Comment by Injodikaran** [comment]
@SilverMoos 
@capiaghi

**Comment by Injodikaran** [comment]
@capiaghi ,@SilverMoos : Debugging rausnehmen
@capiaghi : Prüfen ob Feld gültige Daten beinhaltet

**Comment by sedi01** [comment]
- Algorithmus verbessert / schneller / fertiggestellt
