### ISSUE TITLE
Service Methoden in GUI einbinden (Model)

### ISSUE THREAD

**Issue by Injodikaran** [Injodikaran/Sudoku#27]

**Comment by Injodikaran** [comment]
Service: Initial Spiel speichern
Neues Spiel: 
byte[][] CreateNewGame()

Neu Starten: 
byte[][] ReloadGame()
-> Initial Spiel wird zurückgegeben

Anzeigen:
byte[][] solveGame(byte[][] game)

Check:
boolean[][] checkGame(byte[][] game) -> Bei falschen Werten: false

Spiel speichern:
void SaveGame(byte[][])
--> JSON File abspeichern mit aktuellem Spielstand mit Bestimmten Namen vom Benutzer ausgewählt

Spiel laden:
Altes spiel anhand Filenamen laden

**Comment by sedi01** [comment]
@SilverMoos : Fängt mit der Implementierung der Service-Methoden an
