### ISSUE TITLE
Einlesen von Spielfeld

### ISSUE THREAD

**Issue by Injodikaran** [Injodikaran/Sudoku#4]

**Comment by Injodikaran** [comment]
Neues Spiel:
byte[][] CreateNewGame()
Byte Array übergeben und darstellen

**Comment by sedi01** [comment]
- Testprojekt offen
- Installation von JavaFX schlägt immer noch fehl. 
- Nach Behebung des Problems wird weitergemacht
- Algorithmus zur Einbindung in JavaFX vorhanden
